
GET http://localhost:4000/users

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "lastname": "Doe",
    "email": "test3@test.com",
    "password": "Azerty12345!"
}

###
//createGame
POST http://localhost:4000/api/games

###
//getGameStatus
GET http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2
###
//resetGame
PUT http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2/reset



###
//-----Wining game for player 1-----
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
POST http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2/moves
Content-Type: application/json

{ 
    "playerId": "bb37ae91-be0f-4920-ab71-3e5c937b0319", 
    "row": 1, 
    "col": 1
}

###
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
POST http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2/moves
Content-Type: application/json

{ 
    "playerId": "df09c03a-3702-45bf-8ee0-a88138436624", 
    "row": 0, 
    "col": 0
}

###
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
POST http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2/moves
Content-Type: application/json

{ 
    "playerId": "bb37ae91-be0f-4920-ab71-3e5c937b0319", 
    "row": 0, 
    "col": 1
}

###
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
POST http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2/moves
Content-Type: application/json

{ 
    "playerId": "df09c03a-3702-45bf-8ee0-a88138436624", 
    "row": 2, 
    "col": 2
}

###
//-----winning here-----
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
POST http://localhost:4000/api/games/23dabc9e-bc9b-4941-b47c-94e3549b92e2/moves
Content-Type: application/json

{ 
    "playerId": "bb37ae91-be0f-4920-ab71-3e5c937b0319", 
    "row": 2, 
    "col": 1
}
