
GET http://localhost:4000/users

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "lastname": "Doe",
    "email": "test3@test.com",
    "password": "Azerty12345!"
}

### Request JSON
GET http://localhost:4000/data
Accept: application/json

### Request CSV
GET http://localhost:4000/data
Accept: text/csv

### Request XML
GET http://localhost:4000/data
Accept: application/xml

### Request YAML
GET http://localhost:4000/data
Accept: application/x-yaml


###
//create a Game
POST http://localhost:4000/api/games

###
//get the Game
GET http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588
###
//reset the Game
PATCH http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588
Content-Type: application/json

{
    "currentPlayer": "7d9736de-5949-4f9b-a4ef-54d2bd7db288",
    "board" : null,
    "movesCount": 0,
    "gameState": "inProgress"
}


###
//-----Wining game for player 1-----
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
PATCH http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588/moves
Content-Type: application/json

{ 
    "playerId": "7d9736de-5949-4f9b-a4ef-54d2bd7db288", 
    "row": 1, 
    "col": 1
}

###
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
PATCH http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588/moves
Content-Type: application/json

{ 
    "playerId": "dda30265-d4df-41d2-b151-e5e8f335f830", 
    "row": 0, 
    "col": 0
}

###
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
PATCH http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588/moves
Content-Type: application/json

{ 
    "playerId": "7d9736de-5949-4f9b-a4ef-54d2bd7db288", 
    "row": 0, 
    "col": 1
}

###
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
PATCH http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588/moves
Content-Type: application/json

{ 
    "playerId": "dda30265-d4df-41d2-b151-e5e8f335f830", 
    "row": 2, 
    "col": 2
}

###
//-----winning here-----
//Replace {gameId} with the actual game ID, {playerId} with the ID of the player making the move, {row} with the row number (0-2), and {col} with the column number (0-2).
PATCH http://localhost:4000/api/games/617de8ae-40a7-47f1-a545-fee3a6dcd588/moves
Content-Type: application/json

{ 
    "playerId": "7d9736de-5949-4f9b-a4ef-54d2bd7db288", 
    "row": 2, 
    "col": 1
}
